# Generated by Django 6.0.4 on 2026-04-12 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='degree',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
